### PR TITLE
fix(calendar): Fix `Schedule` error when no events

### LINKED ISSUE #191: [Bug] Schedule returns undefined value
### What did you expect to happen?

Empty/unpopulated schedule should show up

### What happened?

The schedule currently returns undefined if number of events = 0

### Scope

Events

### What browsers are you seeing the problem on?

_No response_

### Relevant log output

_No response_

### PR DESCRIPTION
**Pull request by Spaceface16518**
Since actual track instances (like "General", etc) are computed from the available appointments, the scheduler can't form groups if there are no appointments available because it never expects there to be no instances of a group when a group is specified. In reality, this is a bug in the scheduler component itself, and should be fixed a different way, perhaps by patching React Scheduler itself, but this will fix it for now by not attempting to render groupings when there are no groupings available.

fixes #191

### CODE REVIEW

File: pages/schedule/index.tsx [hunk 1]
```diff
@@ -272,9 +272,18 @@ export default function Calendar(props: { scheduleCard: ScheduleEvent[] }) {
                 <Toolbar />
                 <DateNavigator />
                 <TodayButton />
-                <GroupingState grouping={grouping} groupByDate={() => true} />
-                <IntegratedGrouping />
-                <GroupingPanel />
+                {
+                  // since tracks are computed from entries, only show grouping if there are any tracks
+                  uniqueTracks.size > 0 ? (
```
Comment (geeth24) [inline pages/schedule/index.tsx]: your code is breaking: https://hackportal-git-fix-191-acmutd.vercel.app/schedule
`Application Error: A client-side exception has occurred`
Screenshot 2023-02-25 at 11 58 37 PM

**Review by geeth24 — CHANGES_REQUESTED** [review]

File: pages/schedule/index.tsx (hunk 1 above)
Comment (MichaelZhao21) [reply pages/schedule/index.tsx]: So I messed around with this for a lil bit on my local machine and uhhhh for some reason replacing the react fragment tags with an array of components fixes the issue (no clue why):

image

Comment (Spaceface16518) [reply pages/schedule/index.tsx]: Whoops I'm dumb. Should be fixed by 608bc0638d760aaac2e2f0e8dfa877915ee2dfec. Not sure how this slipped through.

Comment (Spaceface16518) [reply pages/schedule/index.tsx]: > So I messed around with this for a lil bit on my local machine and uhhhh for some reason replacing the react fragment tags with an array of components fixes the issue (no clue why):
> 
> image

Oh I didn't see this. 608bc0638d760aaac2e2f0e8dfa877915ee2dfec did not work after all, so I'll do this instead.

**Comment by geeth24** [comment]
still breaking dude...

File: pages/schedule/index.tsx (hunk 1 above)
Comment (Spaceface16518) [reply pages/schedule/index.tsx]: Okay React is still complaining when I do that. The only way I can get it to work is if I render each in separate template braces.

image

It's not horribly ugly but it feels kinda wrong. Does anyone know a better way to render groups of components that have to be rendered in a specific order? I don't know why the nested block syntax isn't working.

Comment (Spaceface16518) [reply pages/schedule/index.tsx]: The issue is that, for some god-forsaken reason, React Scheduler components rely on other components being rendered before them. I don't know why that's a pattern that exists, but it does, so the cleanest solution I can think of is to render each component in separate braces. This makes me very sad.

**Comment by Spaceface16518** [comment]
Yeah I'm very dumb but this will fix it for now, with minimal changes.

File: pages/schedule/index.tsx (hunk 1 above)
Comment (abdullah50053) [reply pages/schedule/index.tsx]: React Scheduler is and has been a garbage library, we've just got to work around its BS until we finish the refactor and can move to a different library or create something custom.

**Review by geeth24 — APPROVED** [review]

**Review by MichaelZhao21 — APPROVED** [review]
lgtm
